### PR TITLE
Patched token check

### PR DESCRIPTION
**Pull request by brucetony**
Aside from various syntax updates and Exception class additions, I rearranged some code in the `_decode_header()` method so that errors are properly parsed. Now when mistakes and errors are encountered, it does not throw the generic BaseException warning.

### CODE REVIEW

**Comment by luigidellaquila** [comment]
Hi @brucetony 

Thank you very much! 
I see you are still working on this PR, so please let me know when it's done, so that I can check and merge it.

As you can see, PyOrient did not have much maintenance lately and is lagging behind compared to OrientDB Core, all the contributions are much appreciated.

Thanks!

Luigi

**Comment by brucetony** [comment]
Once I get the unit tests to all work, I will let you know. Luckily, this package was very well written so the changes required to keep this up to date are minimal, but the tests must be adapted to handle these changes. Happy to help!

**Comment by brucetony** [comment]
I have spent some time trying to get the unit tests to work, but there is an issue with the OGM and transaction tests. Most everything else now works, but I should stress that my changes are specifically for OrientDB 3.1 and 3.2, I have not tested whether it is backward compatible. The primary patches are applied are:

- Refactoring multiple classes in the [messages module](https://github.com/orientechnologies/pyorient/tree/master/pyorient/messages) to avoid circular imports. [There was a TODO listed](https://github.com/orientechnologies/pyorient/blob/9d87be5cc16c1a009c6a723af36d9bf00074edee/pyorient/messages/base.py#L229) for this and decided clear separation of classes into specific modules was not as important as the odd import structure
- [This token check](https://github.com/orientechnologies/pyorient/blob/9d87be5cc16c1a009c6a723af36d9bf00074edee/pyorient/messages/base.py#L232) was refactored into its own method and moved up in the `decode_header()` method. I did this because according to the [updated binary protocol for responses](https://orientdb.org/docs/3.2.x/internals/Network-Binary-Protocol.html#response), token based sessions have an additional string term that needs to be decoded before the actual message can be decoded
- README file was updated with a new section describing OrientDB 3.1+ at the top and I changed some of the files to follow PEP8 style conventions - not all files, only the ones I worked on. I apologize if this makes it difficult to quickly check my changes
- I updated the files/default databases in the ci folder so the unit tests themselves did not need to be completely rewritten and I updated some unit tests to reflect the new changes. As I mentioned above, there are still a lot of failing tests that I have not solved
- New exception classes were made and applied to better reflect the error classes raised by OrientDB

Please let me know if you have any questions or concerns, always happy to help out.

Cheers,
Bruce

**Comment by luigidellaquila** [comment]
Hi @brucetony 

Thank you very much!
I think it all makes sense; the failing tests are a concern, but having some progress in the compatibility with v 3.1 and 3.2 is very important for now, so I'm merging it.

Thanks!

Luigi

**Pull request merged**
